default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('DB_USERNAME', 'default_user') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'default_password') %>
  host: <%= ENV.fetch('DB_HOST', 'default_db') %>

development:
  <<: *default
  database: taskmate_dev

test:
  <<: *default
  database: taskmate_test

production:
  <<: *default
  database: taskmate_prod
